---
# tasks file for first_setup
- name: Install Docker buildx plugin and exporter
  ansible.builtin.apt:
    pkg:
      - docker-buildx
      #- node-exporter

- name: Copy sources to target
  ansible.builtin.copy:
    src: ./docker
    dest: "/home/{{ ansible_user }}/build"
    mode: "0666"

- name: Create config directory
  file:
    path: /miner/ccminer/config
    state: directory
    mode: "0666"

- name: Create config from template
  template:
    src: ./config.json
    dest: "/home/{{ ansible_user }}/build/docker"
    mode: "0666"

- name: Build miner image
  community.docker.docker_image_build:
    path: "/home/{{ ansible_user }}/build/docker"
    name: "{{ docker_miner_builder_image_name }}:{{ docker_miner_builder_image_version }}"
