groups:
- name: opi5
  rules:
  - alert: node_exporter_down
    expr: up{job="node"} == 0
    for: 10s
    annotations:
      title: 'CA Node Exporter Down'
      description: 'CA Node Exporter Down'
    labels:
      severity: 'crit'

  - alert: High_CPU_utiluzation
    expr: node_load1{job="node"} > 0.9
    for: 1m
    annotations:
      title: 'High CPU utiluzation'
      description: 'High CPU utiluzation'
    labels:
      severity: 'crit'

  - alert: High_memory_utiluzation
    expr: ((node_memory_MemAvailable_bytes{job="node"} / node_memory_MemTotal_bytes{job="node"}) * 100) < 10
    for: 1m
    annotations:
      title: 'High memory utiluzation'
      description: 'High memory utiluzation'
    labels:
      severity: 'crit'

  - alert: Disc_space_problem
    expr: ((node_filesystem_avail_bytes{job="node", mountpoint="/",fstype!="rootfs"} / node_filesystem_size_bytes{job="node", mountpoint="/",fstype!="rootfs"}) * 100) < 10
    for: 10m
    annotations:
      title: 'Disk 90% full'
      description: 'Disk 90% full'
    labels:
      severity: 'crit'

  - alert: High_port_incoming_utilization
    expr: (rate(node_network_receive_bytes_total{job="node", device="eth0"}[5m]) / 1024 / 1024) > 150
    for: 5s
    annotations:
      title: 'High port input load'
      description: 'Incoming port load > 150 Mb/s'
    labels:
      severity: 'crit'

  - alert: High_port_outcoming_utilization
    expr: (rate(node_network_transmit_bytes_total{ job="node", device="eth0"}[5m]) / 1024 / 1024) > 150
    for: 5s
    annotations:
      title: High outbound port utilization
      description: 'Outcoming port load > 150 Mb/s'
    labels:
      severity: 'crit'