- name: Install docker environment and build monitoring images
  hosts: raspberrypi5
  gather_facts: true
  become: true
  roles:
    - docker_installer
    - docker_monitoring_builder
    - docker_monitoring_start
