- name: Install docker environment and build miner image
  hosts: orangepi5-1-2
  gather_facts: true
  become: true
  roles:
    - docker_installer
    - docker_miner_builder
    - docker_miner_start
